name: 🔄 CI

on:
  push:
    branches:
      - main
      - alpha
      - beta
      - '[0-9]+.x'
      - '[0-9]+.[0-9]+.x'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  install:
    runs-on: ubuntu-latest

    outputs:
      NODE_VERSION: ${{ steps.nvm.outputs.NODE_VERSION }}

    steps:
      - name: Begin CI...
        uses: actions/checkout@v4

      - name: Read .nvmrc
        run: ver="$(cat .nvmrc)"; echo "NODE_VERSION=$ver" >> $GITHUB_OUTPUT
        id: nvm

      - name: Setup node (.nvmrc)
        uses: actions/setup-node@v4
        with:
          node-version: '${{ steps.nvm.outputs.NODE_VERSION }}'

      - uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ steps.nvm.outputs.NODE_VERSION }}-lock-hash-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

  lint:
    runs-on: ubuntu-latest
    needs: install

    steps:
      - env:
        NODE_VERSION: ${{needs.install.outputs.NODE_VERSION}}

      - name: Start linting...
        uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ $NODE_VERSION }}-lock-hash-${{ hashFiles('**/package-lock.json') }}

      - name: Lint
        run: npm run lint

  test:
    if: false # TODO: remove when tests will fixed
    runs-on: ubuntu-latest
    needs: install

    steps:
      - env:
        NODE_VERSION: ${{needs.install.outputs.NODE_VERSION}}

      - name: Start testing...
        uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ $NODE_VERSION }}-lock-hash-${{ hashFiles('**/package-lock.json') }}

      - name: Test
        run: npm run test:ci

  build:
    runs-on: ubuntu-latest
    needs: install

    steps:
      - env:
        NODE_VERSION: ${{needs.install.outputs.NODE_VERSION}}

      - name: Start building...
        uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ $NODE_VERSION }}-lock-hash-${{ hashFiles('**/package-lock.json') }}

      - name: Build
        run: npm run build
